[project]
name = "orchestra-dbt"
version = "0.1.1"
description = "To be announced!"
authors = [{ name = "Oliver Crawford" }]
readme = "README.md"
requires-python = ">=3.11"
dependencies = ["click>=8.0", "httpx>=0.28.1", "pydantic>=2.12.5"]

[project.scripts]
orchestra-dbt = "orchestra_dbt.cli:main"

[tool.setuptools.packages.find]
where = ["src"]
