[project]
name = "orchestra-dbt"
version = "0.2.0"
description = "Stateful orchestration for dbt Core projects in Orchestra."
authors = [{ name = "Oliver Crawford" }]
readme = "README.md"
requires-python = ">=3.11"
dependencies = ["click", "httpx", "pydantic", "pyyaml"]

[project.optional-dependencies]
dev = [
    "basedpyright",
    "dbt-core",
    "dbt-snowflake", # Change/add adapters for local development requirements.
    "pytest-httpx",
    "pytest",
    "ruff",
]

debug = [
    "awscrt",
    "boto3",
    "graphviz",
]

[project.scripts]
orchestra-dbt = "orchestra_dbt.cli:main"

[tool.basedpyright]
typeCheckingMode = "basic"

[tool.pytest.ini_options]
pythonpath = ["src"]
testpaths = ["tests"]

[tool.setuptools.packages.find]
where = ["src"]

[tool.uv]
package = true
